import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#a413ec",
        "primary-dark": "#7100a6",
        "primary-container": "#f5d9ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#30004a",
        "on-primary-fixed-variant": "#7100a6",
        "primary-fixed": "#f5d9ff",
        "primary-fixed-dim": "#e6b4ff",
        "inverse-primary": "#e6b4ff",
        secondary: "#8141a6",
        "secondary-container": "#da95ff",
        "secondary-fixed": "#f5d9ff",
        "secondary-fixed-dim": "#e6b4ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#632388",
        "on-secondary-fixed": "#30004a",
        "on-secondary-fixed-variant": "#67278c",
        tertiary: "#774800",
        "tertiary-container": "#ffe8d3",
        "tertiary-fixed": "#ffddba",
        "tertiary-fixed-dim": "#ffb866",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#2b1700",
        "on-tertiary-fixed": "#2b1700",
        "on-tertiary-fixed-variant": "#673d00",
        surface: "#ffffff",
        "surface-bright": "#fff7fc",
        "surface-dim": "#e4d6e5",
        "surface-variant": "#ecdeee",
        "surface-container": "#f8e9f9",
        "surface-container-low": "#feefff",
        "surface-container-high": "#f2e4f4",
        "surface-container-highest": "#ecdeee",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#a413ec",
        "on-surface": "#201924",
        "on-surface-variant": "#4f4254",
        "inverse-surface": "#362d39",
        "inverse-on-surface": "#fbecfc",
        background: "#ffffff",
        "on-background": "#201924",
        outline: "#817286",
        "outline-variant": "#d2c1d7",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        sans: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
